name: quant
channels:
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=hb9a14ef_9
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - intelpython=2022.2.0=0
  - libffi=3.3=14
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py39h06a4308_0
  - python=3.9.12=h3996f55_3
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py39h06a4308_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h74280d8_2
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiohttp-cors==0.7.0
    - aiorwlock==1.3.0
    - aiosignal==1.2.0
    - anyio==3.6.2
    - asgiref==3.5.2
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - blessed==1.19.1
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.0.4
    - cloudpickle==2.2.0
    - colorful==0.5.4
    - contourpy==1.0.5
    - cycler==0.11.0
    - distlib==0.3.6
    - dm-tree==0.1.7
    - dnspython==2.2.1
    - docker-pycreds==0.4.0
    - fastapi==0.85.1
    - filelock==3.8.0
    - flatbuffers==22.9.24
    - fonttools==4.38.0
    - frozenlist==1.3.1
    - fsspec==2022.10.0
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-api-core==2.10.2
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.4
    - gpustat==1.0.0
    - graphql-core==3.2.3
    - grpcio==1.43.0
    - gym==0.23.1
    - gym-notices==0.0.8
    - h11==0.14.0
    - h5py==3.7.0
    - idna==3.4
    - imageio==2.22.2
    - importlib-metadata==5.0.0
    - jsonschema==4.16.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - lz4==4.0.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - msgpack==1.0.4
    - multidict==6.0.2
    - networkx==2.8.7
    - numpy==1.23.4
    - nvidia-ml-py==11.495.46
    - oauthlib==3.2.2
    - opencensus==0.11.0
    - opencensus-context==0.1.3
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.5.1
    - pathtools==0.1.2
    - pillow==9.2.0
    - platformdirs==2.5.2
    - prometheus-client==0.13.1
    - promise==2.3
    - protobuf==3.19.6
    - psutil==5.9.3
    - py-spy==0.3.14
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pyjwt==2.6.0
    - pymongo==4.3.2
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.5
    - pywavelets==1.4.1
    - pyyaml==6.0
    - ray==2.0.1
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.3
    - sentry-sdk==1.10.1
    - setproctitle==1.3.2
    - sgqlc==16.0
    - shinny-structlog==0.0.4
    - shortuuid==1.0.9
    - simplejson==3.17.6
    - six==1.16.0
    - smart-open==6.2.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - starlette==0.20.4
    - tabulate==0.9.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - tifffile==2022.10.10
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - uvicorn==0.16.0
    - virtualenv==20.16.5
    - wandb==0.13.4
    - wcwidth==0.2.5
    - websockets==10.3
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - yarl==1.8.1
    - zipp==3.10.0
